<MenuScreen>:
    BoxLayout:
        size_hint: None, None
        size: min(root.width - 100, 300), 100
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        Button:
            text: 'Start'
            on_press: root.manager.current = 'settings'

<SettingsScreen>:
    grid: Grid
    GridLayout:
        id: Grid
        size_hint: None,None
        size: max(min(root.width,root.height)/3*2,200),max(min(root.width,root.height)/3*2,200)
        pos_hint: {"center_x":0.5, "center_y":0.5}
        cols: root.w



    BoxLayout:
        size_hint: None,None
        size: 100,50
        #pos_hint: {"x":0.03,"top":0.97}
        x: max(10,root.width/100*3)
        top: root.height- max(10,root.height/100*3)
        Button:
            text: 'Back to menu'
            on_press: root.manager.current = 'menu'
